language: python
python:
  - "2.7"

before_install:
 # Install RDKit from source (Release_2014_03_1)
 # Follow the pattern in rdkit/.travis.yml on GitHub
 - clone=`pwd`
 - cd ~
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex bison build-essential python-numpy cmake python-dev sqlite3 libsqlite3-dev libboost-dev libboost-python-dev libboost-regex-dev python-imaging openjdk-7-jdk swig junit
 - wget https://github.com/rdkit/rdkit/archive/Release_2014_03_1.tar.gz
 - tar -xzf Release_2014_03_1.tar.gz
 - cd rdkit-Release_2014_03_1/
 - export RDBASE=`pwd`
 - export PYTHONPATH=${PYTHONPATH}:${RDBASE}
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${RDBASE}/lib
 - mkdir build
 - cd build
 - mkdir $RDBASE/External/java_lib
 - cp /usr/share/java/junit.jar $RDBASE/External/java_lib
 - ls -l $RDBASE/External/java_lib
 - cmake ..
 - make -j2
 - make install

install:
 - cd $clone
 - python setup.py install

script:
 - nosetests
