language: python
python:
 - "2.7"

before_install:

 # Install RDKit from source (Release_2014_03_1)
 # Follow the pattern in rdkit/.travis.yml on GitHub
 - clone=`pwd`
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex bison build-essential python-numpy cmake python-dev sqlite3 libsqlite3-dev libboost-dev libboost-python-dev libboost-regex-dev python-imaging openjdk-7-jdk swig junit
 - cd ~
 - git clone https://github.com/rdkit/rdkit.git rdkit/rdkit
 - cd rdkit/rdkit
 - git checkout tags/Release_2014_03_1
 - export RDBASE=`pwd`
 - export PYTHONPATH=${PYTHONPATH}:${RDBASE}
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${RDBASE}/lib
 - mkdir build
 - cd build
 - mkdir $RDBASE/External/java_lib
 - cp /usr/share/java/junit.jar $RDBASE/External/java_lib
 - ls -l $RDBASE/External/java_lib
 - cmake -D RDK_BUILD_CPP_TESTS=OFF ..
 - make -j2
 - make install

 # Install code analysis tools
 - pip install pep8
 - pip install pyflakes

install:
 - cd $clone
 - python setup.py install

script:
 - nosetests
 - pep8 rdkit_utils
 - pyflakes rdkit_utils
